import type { Question } from '@/types';

function makeId(prefix: string, n: number): string {
  return `seed_${prefix}_${n}`;
}

const now = new Date().toISOString();

export const EXTRA_LEVEL_1_QUESTIONS: Question[] = [
  {
    id: makeId('l1', 11), hash: 'l1_q11', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'variables',
    question: 'What is the correct way to assign the value 50 to a variable named `score`?',
    options: ['int score == 50;', 'int score = 50;', 'score := 50;', 'set score = 50;'],
    correct_answer: 'int score = 50;',
    explanation: 'In C, the assignment operator is a single `=` sign. The type `int` must be specified when declaring the variable.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 12), hash: 'l1_q12', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'arithmetic',
    question: 'What is the result of `5 + 2 * 3` in C?',
    options: ['21', '11', '15', '10'],
    correct_answer: '11',
    explanation: 'Multiplication has higher precedence than addition, so `2 * 3` is evaluated first (6), and then added to 5.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 13), hash: 'l1_q13', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'variables',
    question: 'Which of the following is NOT a valid data type in C?',
    options: ['int', 'float', 'char', 'string'],
    correct_answer: 'string',
    explanation: 'C does not have a built-in `string` type; strings are represented as arrays of characters (`char[]`).',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 14), hash: 'l1_q14', type: 'fill_blank', level: 1, difficulty: 1,
    topic_tag: 'arithmetic',
    question: 'To divide `10` by `2` in C, use the ___ operator.',
    correct_answer: '/',
    explanation: 'The `/` operator is used for division in C and most other programming languages.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 15), hash: 'l1_q15', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'variables',
    question: 'What happens if you use a variable before assigning a value to it in C?',
    options: ['It defaults to 0', 'It results in undefined behavior (garbage value)', 'The compiler throws a syntax error', 'It defaults to null'],
    correct_answer: 'It results in undefined behavior (garbage value)',
    explanation: 'Uninitialized variables in C contain whatever "garbage" data was left in that memory location.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 16), hash: 'l1_q16', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'arithmetic',
    question: 'What does `x++` do?',
    options: ['Adds 2 to x', 'Subtracts 1 from x', 'Increments x by 1', 'Returns an error'],
    correct_answer: 'Increments x by 1',
    explanation: 'The `++` operator is shorthand for `x = x + 1`.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 17), hash: 'l1_q17', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'variables',
    question: 'How do you declare a single character variable in C?',
    options: ['char grade = \'A\';', 'char grade = "A";', 'character grade = \'A\';', 'string grade = \'A\';'],
    correct_answer: 'char grade = \'A\';',
    explanation: 'In C, single characters use the `char` type and are enclosed in single quotes `\'A\'`.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 18), hash: 'l1_q18', type: 'fill_blank', level: 1, difficulty: 1,
    topic_tag: 'variables',
    question: 'A variable named `total_amount` uses ___ case naming convention.',
    correct_answer: 'snake',
    explanation: '`snake_case` separates words with an underscore, which is common in C.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 19), hash: 'l1_q19', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'arithmetic',
    question: 'If `int a = 10; a -= 3;`, what is `a` now?',
    options: ['13', '7', '3', '10'],
    correct_answer: '7',
    explanation: '`a -= 3` is shorthand for `a = a - 3`, so 10 - 3 is 7.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 20), hash: 'l1_q20', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'variables',
    question: 'Which symbol is used for comments in C (single line)?',
    options: ['//', '#', '--', '/*'],
    correct_answer: '//',
    explanation: 'Two forward slashes `//` are used to comment out a single line in C.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  }
];

export const EXTRA_LEVEL_2_QUESTIONS: Question[] = [
  {
    id: makeId('l2', 11), hash: 'l2_q11', type: 'mcq', level: 2, difficulty: 2,
    topic_tag: 'control_flow',
    question: 'What is the logical AND operator in C?',
    options: ['&&', '||', 'AND', '&'],
    correct_answer: '&&',
    explanation: '`&&` requires both conditions to be true. A single `&` is a bitwise operator.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 12), hash: 'l2_q12', type: 'multiple_select', level: 2, difficulty: 2,
    topic_tag: 'control_flow',
    question: 'Which of these are relational operators? (Select all that apply)',
    options: ['==', '!=', '>=', '++'],
    correct_answer: ['==', '!=', '>='],
    explanation: '`==`, `!=`, and `>=` compare two values. `++` is an arithmetic increment operator.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 13), hash: 'l2_q13', type: 'mcq', level: 2, difficulty: 2,
    topic_tag: 'loops',
    question: 'What are the three components of a `for` loop header?',
    options: ['Initialization, Condition, Increment', 'Start, End, Step', 'Setup, Execute, Finish', 'Declaration, Assignment, Output'],
    correct_answer: 'Initialization, Condition, Increment',
    explanation: 'A `for` loop has three parts: `for (initialization; condition; increment)`.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 14), hash: 'l2_q14', type: 'fill_blank', level: 2, difficulty: 2,
    topic_tag: 'control_flow',
    question: 'To check if `a` is equal to `b`, use the ___ operator.',
    correct_answer: '==',
    explanation: '`==` is the equality operator, whereas `=` is used for assignment.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 15), hash: 'l2_q15', type: 'mcq', level: 2, difficulty: 2,
    topic_tag: 'arrays',
    question: 'If you declare `int numbers[10];`, what is the maximum valid index?',
    options: ['10', '9', '11', '8'],
    correct_answer: '9',
    explanation: 'Since arrays are zero-indexed, an array of size 10 has indices ranging from 0 to 9.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 16), hash: 'l2_q16', type: 'multiple_select', level: 2, difficulty: 2,
    topic_tag: 'loops',
    question: 'Which of the following loops evaluates the condition BEFORE executing the body? (Select all that apply)',
    options: ['while', 'for', 'do-while'],
    correct_answer: ['while', 'for'],
    explanation: 'Both `while` and `for` check the condition first. `do-while` executes the body first, then checks.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 17), hash: 'l2_q17', type: 'mcq', level: 2, difficulty: 2,
    topic_tag: 'control_flow',
    question: 'What is the logical OR operator in C?',
    options: ['||', 'OR', '|', '&&'],
    correct_answer: '||',
    explanation: '`||` is the logical OR operator, which evaluates to true if at least one condition is true.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 18), hash: 'l2_q18', type: 'mcq', level: 2, difficulty: 2,
    topic_tag: 'arrays',
    question: 'What happens if you assign a value to `arr[-1]` in C?',
    options: ['Syntax error', 'Undefined behavior (memory corruption)', 'The array wraps around', 'It creates a new element at the start'],
    correct_answer: 'Undefined behavior (memory corruption)',
    explanation: 'C does not perform bounds checking. Writing to a negative index will overwrite memory outside the array.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 19), hash: 'l2_q19', type: 'fill_blank', level: 2, difficulty: 2,
    topic_tag: 'loops',
    question: 'The keyword used to skip the rest of the loop body and jump to the next iteration is ___.',
    correct_answer: 'continue',
    explanation: '`continue` skips the current iteration and evaluates the loop condition again.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 20), hash: 'l2_q20', type: 'mcq', level: 2, difficulty: 2,
    topic_tag: 'control_flow',
    question: 'Can you use a `switch` statement on a `float` variable?',
    options: ['Yes', 'No, only integers and characters', 'Yes, but it is slow', 'No, only strings'],
    correct_answer: 'No, only integers and characters',
    explanation: 'In C, `switch` expressions must evaluate to an integral type (int, char, enum). Floats are not allowed.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  }
];

export const EXTRA_LEVEL_3_QUESTIONS: Question[] = [
  {
    id: makeId('l3', 11), hash: 'l3_q11', type: 'code_output', level: 3, difficulty: 3,
    topic_tag: 'loops',
    question: 'What is the output?',
    code_snippet: 'int sum = 0;\nfor (int i = 0; i < 3; i++) {\n  sum += i * 2;\n}\nprintf("%d", sum);',
    options: ['6', '0', '4', '8'],
    correct_answer: '6',
    explanation: 'i=0: sum=0. i=1: sum=2. i=2: sum=6. Total sum is 6.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 12), hash: 'l3_q12', type: 'debugging', level: 3, difficulty: 3,
    topic_tag: 'control_flow',
    question: 'Identify the bug:',
    code_snippet: 'int x = 5;\nif (x = 10) {\n  printf("Ten");\n} else {\n  printf("Not Ten");\n}',
    options: ['x = 10 assigns instead of comparing (==)', 'Syntax error on printf', 'Missing brackets', 'Variables cannot be modified in if'],
    correct_answer: 'x = 10 assigns instead of comparing (==)',
    explanation: 'Using `=` instead of `==` inside an `if` assigns 10 to x, which evaluates to true. It will always print "Ten".',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 13), hash: 'l3_q13', type: 'mcq', level: 3, difficulty: 3,
    topic_tag: 'arrays',
    question: 'How do you find the number of elements in an integer array `arr` in C?',
    options: ['arr.length', 'sizeof(arr) / sizeof(arr[0])', 'len(arr)', 'arr.size()'],
    correct_answer: 'sizeof(arr) / sizeof(arr[0])',
    explanation: 'C arrays do not have a built-in `.length` property. You divide the total byte size by the size of one element.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 14), hash: 'l3_q14', type: 'multiple_select', level: 3, difficulty: 3,
    topic_tag: 'algorithms',
    question: 'Which of the following are true about linear search? (Select all that apply)',
    options: ['It works on unsorted arrays', 'It requires the array to be sorted', 'It compares each element sequentially', 'It is faster than binary search'],
    correct_answer: ['It works on unsorted arrays', 'It compares each element sequentially'],
    explanation: 'Linear search simply checks one by one, so it works on unsorted data but is slower than binary search.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 15), hash: 'l3_q15', type: 'code_output', level: 3, difficulty: 3,
    topic_tag: 'arrays',
    question: 'What is the output?',
    code_snippet: 'int arr[] = {2, 4, 6, 8};\nprintf("%d", arr[1] + arr[2]);',
    options: ['10', '6', '12', '14'],
    correct_answer: '10',
    explanation: 'arr[1] is 4, arr[2] is 6. 4 + 6 = 10.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 16), hash: 'l3_q16', type: 'debugging', level: 3, difficulty: 3,
    topic_tag: 'loops',
    question: 'Find the logical bug in this factorial code:',
    code_snippet: 'int n = 4, fact = 0;\nfor (int i = 1; i <= n; i++) {\n  fact *= i;\n}\nprintf("%d", fact);',
    options: ['fact should be initialized to 1', 'The loop should start at 0', 'i <= n should be i < n', 'fact should be float'],
    correct_answer: 'fact should be initialized to 1',
    explanation: 'If `fact` is initialized to 0, multiplying it by anything will always result in 0. It must be initialized to 1.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 17), hash: 'l3_q17', type: 'mcq', level: 3, difficulty: 3,
    topic_tag: 'loops',
    question: 'What is a "fencepost error" (or off-by-one error)?',
    options: ['When a loop iterates one time too many or too few', 'When a variable is undefined', 'When a semi-colon is missing', 'When an array is empty'],
    correct_answer: 'When a loop iterates one time too many or too few',
    explanation: 'An off-by-one error occurs when logic (like `<` instead of `<=`) causes a loop to run one extra or one fewer times.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 18), hash: 'l3_q18', type: 'code_output', level: 3, difficulty: 3,
    topic_tag: 'control_flow',
    question: 'What does this print?',
    code_snippet: 'int a = 5;\nif (a < 10) {\n  if (a > 3) printf("A");\n  else printf("B");\n} else {\n  printf("C");\n}',
    options: ['A', 'B', 'C', 'Nothing'],
    correct_answer: 'A',
    explanation: 'Since 5 < 10 is true, it enters the outer if. Since 5 > 3 is true, it prints "A".',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 19), hash: 'l3_q19', type: 'mcq', level: 3, difficulty: 3,
    topic_tag: 'algorithms',
    question: 'To find the minimum value in an array, what should you initialize your `min` variable to?',
    options: ['The first element of the array', '0', '-1', '100'],
    correct_answer: 'The first element of the array',
    explanation: 'Initializing `min` to `arr[0]` ensures that it starts with a valid value from the array. Initializing to 0 might fail if all elements are positive.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 20), hash: 'l3_q20', type: 'multiple_select', level: 3, difficulty: 3,
    topic_tag: 'loops',
    question: 'Which of the following will cause an infinite loop? (Select all that apply)',
    options: ['for(;;)', 'while(1)', 'do {} while(0)', 'for(int i=0; i<10; i--)'],
    correct_answer: ['for(;;)', 'while(1)', 'for(int i=0; i<10; i--)'],
    explanation: '`while(1)` and `for(;;)` are explicitly infinite. `i--` when `i` starts at 0 and goes while `<10` will keep decreasing into negative numbers indefinitely.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  }
];

export const EXTRA_LEVEL_4_QUESTIONS: Question[] = [
  {
    id: makeId('l4', 11), hash: 'l4_q11', type: 'code_output', level: 4, difficulty: 4,
    topic_tag: 'algorithms',
    question: 'What does this code do?',
    code_snippet: 'int t = a;\na = b;\nb = t;',
    options: ['Swaps the values of a and b', 'Deletes a and b', 'Makes a and b equal to t', 'Causes an error'],
    correct_answer: 'Swaps the values of a and b',
    explanation: 'This is the standard pattern using a temporary variable `t` to swap `a` and `b` safely.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 12), hash: 'l4_q12', type: 'debugging', level: 4, difficulty: 4,
    topic_tag: 'atm_project',
    question: 'In an ATM program, why might the following withdrawal logic be flawed?',
    code_snippet: 'if (withdraw_amount <= balance) {\n  balance -= withdraw_amount;\n  printf("Success");\n}',
    options: ['It does not check if withdraw_amount is negative', 'It does not use a loop', 'The subtraction is backwards', 'Variables should be floats'],
    correct_answer: 'It does not check if withdraw_amount is negative',
    explanation: 'If `withdraw_amount` is negative (e.g., -500), `- (-500)` will ADD money to the balance. A check for amount > 0 is essential.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 13), hash: 'l4_q13', type: 'mcq', level: 4, difficulty: 4,
    topic_tag: 'algorithms',
    question: 'Why is avoiding "Magic Numbers" a best practice?',
    options: ['They make code harder to read and update', 'They slow down the compiler', 'They cause runtime crashes', 'They consume more memory'],
    correct_answer: 'They make code harder to read and update',
    explanation: 'A magic number is a hardcoded value (like 3.14). Using named constants (like `PI`) makes the code self-documenting and easier to change.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 14), hash: 'l4_q14', type: 'multiple_select', level: 4, difficulty: 4,
    topic_tag: 'arrays',
    question: 'Which of the following array initialization methods are valid in C? (Select all that apply)',
    options: ['int arr[3] = {1, 2, 3};', 'int arr[] = {1, 2, 3};', 'int arr[3] = {1, 2};', 'int arr[2] = {1, 2, 3};'],
    correct_answer: ['int arr[3] = {1, 2, 3};', 'int arr[] = {1, 2, 3};', 'int arr[3] = {1, 2};'],
    explanation: 'You can explicitly size, auto-size `[]`, or partially initialize (the rest become 0). Providing more elements than the size causes an error.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 15), hash: 'l4_q15', type: 'fill_blank', level: 4, difficulty: 4,
    topic_tag: 'loops',
    question: 'A nested loop means there is a loop placed ___ another loop.',
    correct_answer: 'inside',
    explanation: 'Nested loops are loops within loops, commonly used for multidimensional arrays or patterns.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 16), hash: 'l4_q16', type: 'code_output', level: 4, difficulty: 4,
    topic_tag: 'algorithms',
    question: 'What is the output?',
    code_snippet: 'int arr[] = {2, 2, 2};\nint product = 1;\nfor(int i = 0; i < 3; i++) {\n  product *= arr[i];\n}\nprintf("%d", product);',
    options: ['8', '6', '1', '4'],
    correct_answer: '8',
    explanation: 'This computes the product: 1 * 2 * 2 * 2 = 8.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 17), hash: 'l4_q17', type: 'debugging', level: 4, difficulty: 4,
    topic_tag: 'arrays',
    question: 'Why does this code crash?',
    code_snippet: 'int n = 5;\nint arr[n];\nfor(int i = 1; i <= n; i++) {\n  arr[i] = i;\n}',
    options: ['It accesses arr[5] which is out of bounds', 'n cannot be used to size an array', 'i must start at 0', 'arr should be initialized'],
    correct_answer: 'It accesses arr[5] which is out of bounds',
    explanation: 'Valid indices are 0 to 4. Accessing `arr[5]` goes out of bounds. While `i` starting at 1 is poor practice, the crash is specifically out of bounds.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 18), hash: 'l4_q18', type: 'mcq', level: 4, difficulty: 4,
    topic_tag: 'atm_project',
    question: 'In the ATM switch statement, what is the role of the `default:` case?',
    options: ['To handle invalid user input (e.g., option 5)', 'To exit the program', 'To check the balance', 'To print a welcome message'],
    correct_answer: 'To handle invalid user input (e.g., option 5)',
    explanation: 'The `default` case acts as a fallback for any choices that don\'t match valid cases, protecting against invalid input.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 19), hash: 'l4_q19', type: 'fill_blank', level: 4, difficulty: 4,
    topic_tag: 'algorithms',
    question: 'To find the maximum element, you typically initialize your max variable to the ___ element of the array.',
    correct_answer: 'first',
    explanation: 'Initializing to the first element (`arr[0]`) ensures you are comparing against a valid baseline from the dataset.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 20), hash: 'l4_q20', type: 'mcq', level: 4, difficulty: 4,
    topic_tag: 'control_flow',
    question: 'What is an "edge case" in software logic?',
    options: ['A rare or extreme operating parameter that might cause bugs', 'A feature for advanced users', 'A loop that never ends', 'A syntax error at the end of a file'],
    correct_answer: 'A rare or extreme operating parameter that might cause bugs',
    explanation: 'Edge cases occur at the extreme ends of possible inputs (e.g., withdrawing exactly your full balance, or entering a negative amount).',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  }
];
