// ============================================
// BroQuiz — Seed / Fallback Questions
// All derived from the PDF knowledge sources
// ============================================

import type { Question } from '@/types';

function makeId(prefix: string, n: number): string {
  return `seed_${prefix}_${n}`;
}

const now = new Date().toISOString();

// ===================== LEVEL 1 — Foundation (8 MCQ + 2 Fill) =====================

export const LEVEL_1_QUESTIONS: Question[] = [
  {
    id: makeId('l1', 1), hash: 'l1_q1', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'variables',
    question: 'What does the following code store in the variable `result`?\n\n`int result = number1 + number2;` (where number1=3, number2=5)',
    options: ['35', '8', '3', 'An error'],
    correct_answer: '8',
    explanation: 'The + operator adds the values of number1 (3) and number2 (5), storing 8 in result. Variables hold values in memory, and arithmetic operations produce new values.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 2), hash: 'l1_q2', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'variables',
    question: 'In programming, a variable is best described as:',
    options: ['A fixed mathematical constant', 'A named container that stores data in memory', 'A type of loop', 'A function that prints output'],
    correct_answer: 'A named container that stores data in memory',
    explanation: 'Variables are named memory containers. When you declare a variable like `int age = 25;`, you are creating a labeled box in memory that holds the value 25.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 3), hash: 'l1_q3', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'arithmetic',
    question: 'What is the result of `17 % 5` in C?',
    options: ['3', '2', '3.4', '5'],
    correct_answer: '2',
    explanation: 'The modulo operator (%) returns the remainder of integer division. 17 ÷ 5 = 3 remainder 2, so 17 % 5 = 2.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 4), hash: 'l1_q4', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'variables',
    question: 'Which of the following is a valid variable name in C?',
    options: ['2ndValue', 'my_score', 'int', 'first-name'],
    correct_answer: 'my_score',
    explanation: 'Variable names must start with a letter or underscore, cannot be reserved keywords (like `int`), and cannot contain hyphens. `my_score` follows all naming rules.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 5), hash: 'l1_q5', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'variables',
    question: 'What does IPO stand for in programming?',
    options: ['International Programming Organization', 'Input-Process-Output', 'Integer-Pointer-Object', 'Internal Program Operation'],
    correct_answer: 'Input-Process-Output',
    explanation: 'The IPO model is a fundamental concept: programs take Input, Process it using logic and operations, and produce Output. Every program follows this pattern.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 6), hash: 'l1_q6', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'arithmetic',
    question: 'What will `int x = 10 / 3;` store in x?',
    options: ['3.33', '3', '4', '10'],
    correct_answer: '3',
    explanation: 'In C, dividing two integers performs integer division — the decimal part is truncated (not rounded). 10 / 3 = 3.33... becomes 3.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 7), hash: 'l1_q7', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'variables',
    question: 'What data type would you use to store a decimal number like 3.14 in C?',
    options: ['int', 'char', 'float', 'bool'],
    correct_answer: 'float',
    explanation: '`float` (or `double`) is used for decimal/floating-point numbers. `int` only stores whole numbers, `char` stores single characters.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 8), hash: 'l1_q8', type: 'mcq', level: 1, difficulty: 1,
    topic_tag: 'arithmetic',
    question: 'In the expression `a = a + 1;`, what happens?',
    options: ['It causes an error because a appears on both sides', 'The old value of a is incremented by 1 and stored back', 'It creates a new variable', 'Nothing happens'],
    correct_answer: 'The old value of a is incremented by 1 and stored back',
    explanation: 'The right side `a + 1` is evaluated first using the current value of a, then the result is assigned back to a. This is a common pattern for incrementing.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 9), hash: 'l1_q9', type: 'fill_blank', level: 1, difficulty: 1,
    topic_tag: 'arithmetic',
    question: 'Complete the expression to add two numbers:\n\n`int result = num1 ___ num2;`',
    correct_answer: '+',
    explanation: 'The + operator performs addition. `num1 + num2` adds the values of both variables.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l1', 10), hash: 'l1_q10', type: 'fill_blank', level: 1, difficulty: 1,
    topic_tag: 'variables',
    question: 'To declare an integer variable called `age` with value 25, write:\n\n`___ age = 25;`',
    correct_answer: 'int',
    explanation: '`int` is the keyword used to declare integer variables in C. The full declaration `int age = 25;` creates a variable named age and assigns it the value 25.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
];

// ===================== LEVEL 2 — Logic Builder (5 MCQ + 3 Multiple Select + 2 Fill) =====================

export const LEVEL_2_QUESTIONS: Question[] = [
  {
    id: makeId('l2', 1), hash: 'l2_q1', type: 'mcq', level: 2, difficulty: 2,
    topic_tag: 'control_flow',
    question: 'What will the following code print?\n\n```c\nint x = 15;\nif (x > 10) {\n  printf("Big");\n} else {\n  printf("Small");\n}\n```',
    options: ['Big', 'Small', 'BigSmall', 'Nothing'],
    correct_answer: 'Big',
    explanation: 'Since x=15 and 15 > 10 is true, the if-block executes and prints "Big". The else block is skipped.',
    code_snippet: 'int x = 15;\nif (x > 10) {\n  printf("Big");\n} else {\n  printf("Small");\n}',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 2), hash: 'l2_q2', type: 'mcq', level: 2, difficulty: 2,
    topic_tag: 'control_flow',
    question: 'In a switch statement, what happens if you forget the `break` keyword in a case?',
    options: ['The program crashes', 'Execution falls through to the next case', 'Only the default case runs', 'The compiler throws an error'],
    correct_answer: 'Execution falls through to the next case',
    explanation: 'Without break, execution "falls through" — it continues executing the code in subsequent cases until a break is found or the switch ends. This is a common source of bugs.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 3), hash: 'l2_q3', type: 'mcq', level: 2, difficulty: 2,
    topic_tag: 'loops',
    question: 'How many times will this loop execute?\n\n```c\nfor (int i = 0; i < 5; i++) {\n  printf("%d ", i);\n}\n```',
    options: ['4 times', '5 times', '6 times', 'Infinite times'],
    correct_answer: '5 times',
    explanation: 'The loop starts at i=0 and runs while i < 5. So i takes values 0, 1, 2, 3, 4 — that is 5 iterations.',
    code_snippet: 'for (int i = 0; i < 5; i++) {\n  printf("%d ", i);\n}',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 4), hash: 'l2_q4', type: 'mcq', level: 2, difficulty: 2,
    topic_tag: 'arrays',
    question: 'What is the index of the third element in an array?',
    options: ['3', '2', '1', '0'],
    correct_answer: '2',
    explanation: 'Arrays use zero-based indexing. The first element is at index 0, the second at index 1, and the third at index 2.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 5), hash: 'l2_q5', type: 'mcq', level: 2, difficulty: 2,
    topic_tag: 'loops',
    question: 'What is the key difference between a `while` loop and a `do-while` loop?',
    options: ['while loops are faster', 'do-while always executes at least once', 'while loops cannot use break', 'There is no difference'],
    correct_answer: 'do-while always executes at least once',
    explanation: 'A do-while loop checks the condition AFTER executing the body, so it always runs at least once. A while loop checks BEFORE, so it might not run at all.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 6), hash: 'l2_q6', type: 'multiple_select', level: 2, difficulty: 2,
    topic_tag: 'loops',
    question: 'Which of the following are valid loop types in C? (Select all that apply)',
    options: ['for loop', 'while loop', 'foreach loop', 'do-while loop', 'repeat-until loop'],
    correct_answer: ['for loop', 'while loop', 'do-while loop'],
    explanation: 'C supports three loop types: for, while, and do-while. `foreach` exists in other languages (C#, Java) but not in standard C. `repeat-until` is a Pascal construct.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 7), hash: 'l2_q7', type: 'multiple_select', level: 2, difficulty: 2,
    topic_tag: 'arrays',
    question: 'Which of the following are valid operations on an array in C? (Select all that apply)',
    options: ['Accessing element by index', 'Iterating with a for loop', 'Dynamic resizing at runtime', 'Summation using a loop variable'],
    correct_answer: ['Accessing element by index', 'Iterating with a for loop', 'Summation using a loop variable'],
    explanation: 'You can access elements by index (arr[i]), iterate with loops, and sum elements. Static arrays in C cannot be dynamically resized — that requires dynamic memory allocation.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 8), hash: 'l2_q8', type: 'multiple_select', level: 2, difficulty: 2,
    topic_tag: 'control_flow',
    question: 'Which of the following statements about if/else are TRUE? (Select all that apply)',
    options: ['An if statement can exist without an else', 'else if allows checking multiple conditions', 'You can nest if statements inside each other', 'An else block is always required'],
    correct_answer: ['An if statement can exist without an else', 'else if allows checking multiple conditions', 'You can nest if statements inside each other'],
    explanation: 'An if statement works independently without else. `else if` chains multiple conditions. Nesting is allowed. The else block is optional.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 9), hash: 'l2_q9', type: 'fill_blank', level: 2, difficulty: 2,
    topic_tag: 'arrays',
    question: 'To access the first element of an array called `scores`, you write:\n\n`scores[___]`',
    correct_answer: '0',
    explanation: 'Arrays in C use zero-based indexing. The first element is always at index 0.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l2', 10), hash: 'l2_q10', type: 'fill_blank', level: 2, difficulty: 2,
    topic_tag: 'loops',
    question: 'To exit a loop immediately, use the ___ keyword.',
    correct_answer: 'break',
    explanation: 'The `break` keyword immediately terminates the innermost loop and continues execution after the loop.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
];

// ===================== LEVEL 3 — Code Thinker (3 MCQ + 2 Multi + 3 Code Output + 2 Debug) =====================

export const LEVEL_3_QUESTIONS: Question[] = [
  {
    id: makeId('l3', 1), hash: 'l3_q1', type: 'mcq', level: 3, difficulty: 3,
    topic_tag: 'loops',
    question: 'In a nested loop where the outer loop runs N times and the inner loop runs M times, how many total iterations of the inner loop body occur?',
    options: ['N + M', 'N × M', 'N - M', 'max(N, M)'],
    correct_answer: 'N × M',
    explanation: 'For each iteration of the outer loop, the inner loop runs completely. So if outer runs N times and inner runs M times each, the inner body executes N × M times total.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 2), hash: 'l3_q2', type: 'mcq', level: 3, difficulty: 3,
    topic_tag: 'arrays',
    question: 'What happens when you try to access `arr[10]` in an array declared as `int arr[5];`?',
    options: ['It returns 0', 'It causes an out-of-bounds error / undefined behavior', 'It automatically expands the array', 'The compiler prevents this'],
    correct_answer: 'It causes an out-of-bounds error / undefined behavior',
    explanation: 'Accessing an index beyond the array size is undefined behavior in C. It may read garbage data, crash, or cause subtle bugs. C does not perform bounds checking.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 3), hash: 'l3_q3', type: 'mcq', level: 3, difficulty: 3,
    topic_tag: 'algorithms',
    question: 'In linear search, what is the worst-case scenario?',
    options: ['The element is at the beginning', 'The element is in the middle', 'The element is at the end or not present', 'Linear search has no worst case'],
    correct_answer: 'The element is at the end or not present',
    explanation: 'Linear search checks each element sequentially. The worst case is when the target is at the last position or not in the array at all — requiring all N elements to be checked.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 4), hash: 'l3_q4', type: 'multiple_select', level: 3, difficulty: 3,
    topic_tag: 'loops',
    question: 'Which of the following statements about `break` and `continue` are correct? (Select all that apply)',
    options: ['break exits the entire loop', 'continue skips the rest of the current iteration', 'break can be used in switch statements', 'continue exits the loop', 'break only works in for loops'],
    correct_answer: ['break exits the entire loop', 'continue skips the rest of the current iteration', 'break can be used in switch statements'],
    explanation: 'break terminates the loop entirely and works in switch too. continue skips to the next iteration but does NOT exit the loop. break works in all loop types.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 5), hash: 'l3_q5', type: 'multiple_select', level: 3, difficulty: 3,
    topic_tag: 'algorithms',
    question: 'Which of the following are required steps in a summation algorithm using an array? (Select all that apply)',
    options: ['Initialize a sum variable to 0', 'Loop through each element', 'Add each element to the sum', 'Sort the array first', 'Return or print the sum'],
    correct_answer: ['Initialize a sum variable to 0', 'Loop through each element', 'Add each element to the sum', 'Return or print the sum'],
    explanation: 'Summation requires: (1) init sum=0, (2) iterate through elements, (3) add each to sum, (4) output result. Sorting is NOT required for summation.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 6), hash: 'l3_q6', type: 'code_output', level: 3, difficulty: 3,
    topic_tag: 'loops',
    question: 'What is the output of this code?',
    code_snippet: 'int i;\nfor(i = 1; i <= 5; i++) {\n  if(i == 3) continue;\n  printf("%d ", i);\n}',
    options: ['1 2 3 4 5', '1 2 4 5', '1 2', '3'],
    correct_answer: '1 2 4 5',
    explanation: 'The loop prints i from 1 to 5, but when i==3, `continue` skips the printf for that iteration. So 3 is skipped, and the output is 1 2 4 5.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 7), hash: 'l3_q7', type: 'code_output', level: 3, difficulty: 3,
    topic_tag: 'loops',
    question: 'What is the output of this code?',
    code_snippet: 'int count = 0;\nfor(int i = 1; i <= 3; i++) {\n  for(int j = 1; j <= 2; j++) {\n    count++;\n  }\n}\nprintf("%d", count);',
    options: ['3', '5', '6', '8'],
    correct_answer: '6',
    explanation: 'The outer loop runs 3 times, and for each iteration, the inner loop runs 2 times. Total increments: 3 × 2 = 6.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 8), hash: 'l3_q8', type: 'code_output', level: 3, difficulty: 3,
    topic_tag: 'arrays',
    question: 'What is the output of this code?',
    code_snippet: 'int arr[] = {10, 20, 30, 40, 50};\nint sum = 0;\nfor(int i = 0; i < 5; i++) {\n  sum += arr[i];\n}\nprintf("%d", sum);',
    options: ['100', '150', '50', '200'],
    correct_answer: '150',
    explanation: 'The loop adds all array elements: 10 + 20 + 30 + 40 + 50 = 150. This is the classic summation algorithm pattern.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 9), hash: 'l3_q9', type: 'debugging', level: 3, difficulty: 3,
    topic_tag: 'loops',
    question: 'This code is supposed to print numbers 1 to 5, but it has a bug. What\'s wrong?',
    code_snippet: 'int i = 1;\nwhile(i <= 5) {\n  printf("%d ", i);\n}',
    options: ['i should start at 0', 'Missing i++ inside the loop — causes infinite loop', 'The condition should be i < 5', 'printf syntax is wrong'],
    correct_answer: 'Missing i++ inside the loop — causes infinite loop',
    explanation: 'Without `i++` inside the loop body, i never changes from 1, making the condition `i <= 5` always true. This creates an infinite loop.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l3', 10), hash: 'l3_q10', type: 'debugging', level: 3, difficulty: 3,
    topic_tag: 'control_flow',
    question: 'This switch statement doesn\'t work correctly. Identify the bug:',
    code_snippet: 'int day = 2;\nswitch(day) {\n  case 1:\n    printf("Monday");\n  case 2:\n    printf("Tuesday");\n  case 3:\n    printf("Wednesday");\n  default:\n    printf("Unknown");\n}',
    options: ['The variable day should be a string', 'Missing break statements — causes fall-through', 'case values should start at 0', 'default is not needed'],
    correct_answer: 'Missing break statements — causes fall-through',
    explanation: 'Without break after each case, execution falls through to subsequent cases. When day=2, it prints "Tuesday", then falls through to print "Wednesday" and "Unknown" too.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
];

// ===================== LEVEL 4 — Master Challenge (2 MCQ + 2 Multi + 2 Fill + 2 Code + 2 Debug) =====================

export const LEVEL_4_QUESTIONS: Question[] = [
  {
    id: makeId('l4', 1), hash: 'l4_q1', type: 'mcq', level: 4, difficulty: 4,
    topic_tag: 'atm_project',
    question: 'In the ATM Machine project, which programming concepts are combined to create the menu system?',
    options: ['Only arrays', 'Loop + switch/case + variables', 'Only if/else statements', 'Functions only'],
    correct_answer: 'Loop + switch/case + variables',
    explanation: 'The ATM project uses a loop (to keep the menu running), switch/case (to handle menu choices), and variables (to track balance). This demonstrates the integrative use of all fundamental concepts.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 2), hash: 'l4_q2', type: 'mcq', level: 4, difficulty: 4,
    topic_tag: 'algorithms',
    question: 'What does the DRY principle stand for, and why is it important?',
    options: ['Don\'t Repeat Yourself — reduces code duplication and errors', 'Data Retrieval Yielding — improves database access', 'Direct Resource Yielding — optimizes memory', 'Debug Run Yield — helps testing'],
    correct_answer: 'Don\'t Repeat Yourself — reduces code duplication and errors',
    explanation: 'DRY (Don\'t Repeat Yourself) means avoiding code duplication. Instead of writing the same logic multiple times, use loops, functions, or variables. This reduces bugs and makes code maintainable.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 3), hash: 'l4_q3', type: 'multiple_select', level: 4, difficulty: 4,
    topic_tag: 'atm_project',
    question: 'In an ATM Machine program, which of the following operations should be supported? (Select all that apply)',
    options: ['Check balance', 'Deposit money', 'Withdraw money', 'Sort transactions', 'Exit the program'],
    correct_answer: ['Check balance', 'Deposit money', 'Withdraw money', 'Exit the program'],
    explanation: 'A basic ATM supports checking balance, deposits, withdrawals, and exiting. Sorting transactions is a more advanced feature not covered in the fundamental ATM project.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 4), hash: 'l4_q4', type: 'multiple_select', level: 4, difficulty: 4,
    topic_tag: 'algorithms',
    question: 'Which of the following are true about variable swapping with a temp variable? (Select all that apply)',
    options: ['The temp variable holds one value to prevent data loss', 'You need exactly 3 assignment statements', 'The order of assignments doesn\'t matter', 'Without temp, one original value is overwritten'],
    correct_answer: ['The temp variable holds one value to prevent data loss', 'You need exactly 3 assignment statements', 'Without temp, one original value is overwritten'],
    explanation: 'Swap requires: temp=a; a=b; b=temp; — exactly 3 steps. Without temp, doing a=b; b=a; loses the original value of a. Order matters.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 5), hash: 'l4_q5', type: 'fill_blank', level: 4, difficulty: 4,
    topic_tag: 'algorithms',
    question: 'To swap two variables a and b, the first step is:\n\n`int ___ = a;`',
    correct_answer: 'temp',
    explanation: 'The temp (temporary) variable stores the original value of a before it gets overwritten. This is the classic variable swap pattern.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 6), hash: 'l4_q6', type: 'fill_blank', level: 4, difficulty: 4,
    topic_tag: 'loops',
    question: 'To skip the current iteration and move to the next one in a loop, use the ___ keyword.',
    correct_answer: 'continue',
    explanation: 'The `continue` keyword skips the remaining code in the current iteration and jumps to the next iteration of the loop.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 7), hash: 'l4_q7', type: 'code_output', level: 4, difficulty: 4,
    topic_tag: 'loops',
    question: 'What is the output of this code?',
    code_snippet: 'for(int i = 1; i <= 3; i++) {\n  for(int j = 1; j <= i; j++) {\n    printf("* ");\n  }\n  printf("\\n");\n}',
    options: ['* * *\\n* * *\\n* * *', '*\\n* *\\n* * *', '* * *\\n* *\\n*', '***'],
    correct_answer: '*\\n* *\\n* * *',
    explanation: 'This is a pattern-generating nested loop. When i=1, j prints 1 star. When i=2, j prints 2 stars. When i=3, j prints 3 stars. This creates a right triangle pattern.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 8), hash: 'l4_q8', type: 'code_output', level: 4, difficulty: 4,
    topic_tag: 'arrays',
    question: 'What is the output of this code?',
    code_snippet: 'int arr[] = {5, 3, 8, 1, 9};\nint max = arr[0];\nfor(int i = 1; i < 5; i++) {\n  if(arr[i] > max) {\n    max = arr[i];\n  }\n}\nprintf("%d", max);',
    options: ['5', '9', '1', '8'],
    correct_answer: '9',
    explanation: 'This is a linear search for the maximum value. Starting with max=5, it compares each element: 3<5, 8>5→max=8, 1<8, 9>8→max=9. Final answer: 9.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 9), hash: 'l4_q9', type: 'debugging', level: 4, difficulty: 4,
    topic_tag: 'algorithms',
    question: 'The following code is supposed to swap two variables. Find the bug:',
    code_snippet: 'int a = 10, b = 20;\na = b;        // line 1\nb = a;        // line 2',
    options: ['Line 1 — should declare temp first', 'Line 2 — should be b = temp', 'The logic is correct', 'Line 1 should use == not ='],
    correct_answer: 'Line 1 — should declare temp first',
    explanation: 'After line 1, a becomes 20 (original value 10 is lost). Line 2 sets b = a = 20. Both are 20 now. Fix: use a temp variable to save a\'s original value first.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
  {
    id: makeId('l4', 10), hash: 'l4_q10', type: 'debugging', level: 4, difficulty: 4,
    topic_tag: 'arrays',
    question: 'This code is supposed to find the sum of array elements, but it gives the wrong answer. Identify the bug:',
    code_snippet: 'int arr[] = {1, 2, 3, 4, 5};\nint sum = 1;  // line 1\nfor(int i = 0; i < 5; i++) {\n  sum += arr[i];\n}\nprintf("%d", sum);',
    options: ['Line 1 — sum should be initialized to 0, not 1', 'The loop should start at i = 1', 'The += operator is wrong', 'The array declaration is wrong'],
    correct_answer: 'Line 1 — sum should be initialized to 0, not 1',
    explanation: 'Initializing sum to 1 adds an extra 1 to the result. The correct initialization is sum = 0, which gives: 0+1+2+3+4+5 = 15. With sum=1, you get 16.',
    times_shown: 0, correct_count: 0, created_at: now, status: 'approved',
  },
];

import { EXTRA_LEVEL_1_QUESTIONS, EXTRA_LEVEL_2_QUESTIONS, EXTRA_LEVEL_3_QUESTIONS, EXTRA_LEVEL_4_QUESTIONS } from './more-seed-questions';

// --- All levels combined ---
export const ALL_SEED_QUESTIONS: Record<number, Question[]> = {
  1: [...LEVEL_1_QUESTIONS, ...EXTRA_LEVEL_1_QUESTIONS],
  2: [...LEVEL_2_QUESTIONS, ...EXTRA_LEVEL_2_QUESTIONS],
  3: [...LEVEL_3_QUESTIONS, ...EXTRA_LEVEL_3_QUESTIONS],
  4: [...LEVEL_4_QUESTIONS, ...EXTRA_LEVEL_4_QUESTIONS],
};
